-- 코드를 입력하세요
# (SELECT FLAVOR from ICECREAM_INFO
#     where INGREDIENT_TYPE='fruit_based')
# UNION
# (SELECT FLAVOR from FIRST_HALF
#     where TOTAL_ORDER>3000 order by TOTAL_ORDER desc);

SELECT FIRST_HALF.FLAVOR from FIRST_HALF, ICECREAM_INFO
    where FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR and FIRST_HALF.TOTAL_ORDER>3000 and ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
    order by TOTAL_ORDER desc;