-- 코드를 입력하세요
SELECT
    CAR_ID,
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) as 'AVERAGE_DURATION'
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
group by CAR_ID
having ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) >= 7
order by ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) desc, CAR_ID desc;
-- AVG() 안에 쓰는 게 관건