-- 코드를 입력하세요
# SELECT
#     ANIMAL_INS.NAME,
#     ANIMAL_INS.DATETIME
# from ANIMAL_INS
# group by ANIMAL_INS.NAME
# where ANIMAL_OUTS.ANIMAL_ID is NULL
# -- having not ANIMAL_OUTS.NAME
# -- where ANIMAL_OUTS.ANIMAL_ID != ANIMAL_INS.ANIMAL_ID
# order by ANIMAL_INS.DATETIME desc
# limit 3;
SELECT a.NAME, a.DATETIME
FROM ANIMAL_INS a LEFT JOIN ANIMAL_OUTS b ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE b.ANIMAL_ID IS NULL
ORDER BY a.DATETIME
LIMIT 3;