-- 코드를 입력하세요
select
    PRODUCT.PRODUCT_CODE,
    (PRODUCT.PRICE * SUM(OFFLINE_SALE.SALES_AMOUNT)) as 'SALES'
from PRODUCT, OFFLINE_SALE
where PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
group by PRODUCT.PRODUCT_CODE
order by (PRODUCT.PRICE * SUM(OFFLINE_SALE.SALES_AMOUNT)) desc, PRODUCT_CODE asc;