-- 코드를 입력하세요
SELECT
    ICECREAM_INFO.INGREDIENT_TYPE,
    SUM(FIRST_HALF.TOTAL_ORDER) as 'TOTAL_ORDER'
from FIRST_HALF, ICECREAM_INFO
where FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
group by INGREDIENT_TYPE
order by SUM(FIRST_HALF.TOTAL_ORDER) asc;
-- 총주문량 asc

# select ICECREAM_INFO.INGREDIENT_TYPE, FIRST_HALF.TOTAL_ORDER as 'TOTAL_ORDER'
# from FIRST_HALF, ICECREAM_INFO;